from typing import Generic, TypeVar


T = TypeVar("T")
Row = TypeVar("Row")


class Model: ...


class Field:
    def __init__(self, *args, **kwargs):
        pass


class CharField(Field):
    pass


class IntegerField(Field):
    pass


class ForeignKey(Field):
    pass


class QuerySet(Generic[T, Row]):
    def filter(self, **kwargs): ...
    def get(self, **kwargs): ...
    def get_or_create(self, **kwargs): ...
    def first(self): ...
    def count(self): ...
    def exists(self): ...
    def values(self, *fields): ...
    def values_list(self, *fields, flat: bool = False, named: bool = False): ...
    def annotate(self, **kwargs): ...


class Manager(Generic[T]):
    def filter(self, **kwargs): ...
    def get(self, **kwargs): ...
    def get_or_create(self, **kwargs): ...
    def first(self): ...
    def count(self): ...
    def exists(self): ...
    def values(self, *fields): ...
    def values_list(self, *fields, flat: bool = False, named: bool = False): ...
    def annotate(self, **kwargs): ...
